#!/usr/bin/env bash

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

bar=(
  height=40
  sticky=off
  position=top
  blur_radius=15
  padding_left=10
  padding_right=10
  color=0x7f000000
)

sketchybar --bar "${bar[@]}"

default=(
  padding_left=5
  padding_right=5
  icon.y_offset=1
  label.y_offset=1
  icon.align=center
  label.align=center
  icon.padding_left=5
  icon.padding_right=5
  label.padding_left=5
  label.padding_right=5
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.font="JetBrainsMono Nerd Font:Bold:17.0"
  label.font="JetBrainsMono Nerd Font:Bold:17.0"
)

sketchybar --default "${default[@]}"

mode=(
  label="H"
  icon.drawing=off
  background.height=20
  label.padding_right=6 
  label.color=0xffffffff
  background.corner_radius=5
  background.color=0xffff0000
)

sketchybar --add item mode left \
    --set mode "${mode[@]}" 

sketchybar --add event aerospace_workspace_change
for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change space_windows_change space_change \
        --set space.$sid \
        background.color=0xff8ec07c  \
        background.corner_radius=5 \
        background.height=20 \
        background.drawing=off \
        icon.drawing=off \
        label="$sid" \
        label.padding_right=6 \
        click_script="aerospace workspace $sid" \
        script="$PLUGIN_DIR/aerospace.sh $sid"
done

sketchybar --add item chevron left \
    --set chevron icon= label.drawing=off \
    --add item front_app left \
    --subscribe front_app front_app_switched \
    --set front_app script="$PLUGIN_DIR/front_app.sh" \
    background.color=0xff8ec07c  \
    background.corner_radius=5 \
    background.height=20 \
    background.drawing=on \
    icon.drawing=off \
    label.color=0xff000000

sketchybar --add item clock right \
    --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
    --add item battery right \
    --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
    --subscribe battery system_woke power_source_change

media=(
  script="$PLUGIN_DIR/media.sh"
  updates=on
)

sketchybar --add item media center \
           --set media "${media[@]}" \
           --subscribe media media_change

sketchybar --update
